# Change these first
owner: Gunivers # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Altearn
    url: https://altearn.xyz
  - name: Gunivers
    url: https://gunivers.net
  - name: Fat Man
    check: "tcp-ping"
    url: fm.altearn.xyz
    port: 80
  - name: Little Boy
    check: "tcp-ping"
    url: lb.altearn.xyz
    port: 80

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://altearn.xyz/wp-content/uploads/2020/12/Altearn-Title-Shadow-200x.png
  name: Altearb
  introTitle: "Suivez sur cette page le status en temps réel des serveurs d'Altearn."
  introMessage: Les données sont récupérées en temps réel grâce à Github Actions.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Altearn
      href: https://altearn.xyz
    - title: Gunivers
      href: https://gunivers.net

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - AnandChowdhary
